receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"  

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
